/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AvoirMembreConseilDiscipline
 */
export interface AvoirMembreConseilDiscipline {
    /**
     * 
     * @type {number}
     * @memberof AvoirMembreConseilDiscipline
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof AvoirMembreConseilDiscipline
     */
    idMembreConseil: any;
    /**
     * 
     * @type {number}
     * @memberof AvoirMembreConseilDiscipline
     */
    idConseilDiscipline: any;
    /**
     * 
     * @type {MembreConseil}
     * @memberof AvoirMembreConseilDiscipline
     */
    membreconseil?: any;
    /**
     * 
     * @type {ConseilDiscipline}
     * @memberof AvoirMembreConseilDiscipline
     */
    conseildiscipline?: any;
    /**
     * 
     * @type {BaseModelpropertiescreatedAt}
     * @memberof AvoirMembreConseilDiscipline
     */
    createdAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesupdatedAt}
     * @memberof AvoirMembreConseilDiscipline
     */
    updatedAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesdeletedAt}
     * @memberof AvoirMembreConseilDiscipline
     */
    deletedAt?: any;
}
