/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ClassesCreateBody
 */
export interface ClassesCreateBody {
    /**
     * Terminal
     * @type {string}
     * @memberof ClassesCreateBody
     */
    name?: any;
    /**
     * Tle
     * @type {string}
     * @memberof ClassesCreateBody
     */
    shortName?: any;
    /**
     * C
     * @type {string}
     * @memberof ClassesCreateBody
     */
    speciality?: any;
}
