/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ElevesCreateBody
 */
export interface ElevesCreateBody {
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    firstName: any;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    lastName: any;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    dateDeNaissance: any;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    lieuDeNaissance: any;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    photo?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    sexe: any;
    /**
     * 
     * @type {string}
     * @memberof ElevesCreateBody
     */
    telephone: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof ElevesCreateBody
     */
    solvable: any;
    /**
     * 
     * @type {boolean}
     * @memberof ElevesCreateBody
     */
    redoublant: any;
    /**
     * 
     * @type {number}
     * @memberof ElevesCreateBody
     */
    classeId: any;
}
