/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse4004Error
 */
export interface InlineResponse4004Error {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof InlineResponse4004Error
     */
    email?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof InlineResponse4004Error
     */
    username?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof InlineResponse4004Error
     */
    password?: any;
}
