/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse4044
 */
export interface InlineResponse4044 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse4044
     */
    success?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse4044
     */
    error?: any;
}
