/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2007
     */
    success?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    message?: any;
    /**
     * 
     * @type {Array&lt;Classe&gt;}
     * @memberof InlineResponse2007
     */
    content?: any;
}
