/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ParentsUpdateBody
 */
export interface ParentsUpdateBody {
    /**
     * 
     * @type {number}
     * @memberof ParentsUpdateBody
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    dateDeNaissance?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    lieuDeNaissance?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    photo?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    sexe?: any;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    telephone?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ParentsUpdateBody
     */
    profession?: any;
}
