/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReglementInterieur
 */
export interface ReglementInterieur {
    /**
     * 
     * @type {number}
     * @memberof ReglementInterieur
     */
    id?: any;
    /**
     * Un nouveau reglement interieur
     * @type {string}
     * @memberof ReglementInterieur
     */
    libelle: any;
    /**
     * 
     * @type {BaseModelpropertiescreatedAt}
     * @memberof ReglementInterieur
     */
    createdAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesupdatedAt}
     * @memberof ReglementInterieur
     */
    updatedAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesdeletedAt}
     * @memberof ReglementInterieur
     */
    deletedAt?: any;
}
