/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateNotificationIdBody
 */
export interface UpdateNotificationIdBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateNotificationIdBody
     */
    libelle?: any;
    /**
     * 
     * @type {number}
     * @memberof UpdateNotificationIdBody
     */
    view: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateNotificationIdBody
     */
    email: any;
}
