/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateCoursIdBody
 */
export interface UpdateCoursIdBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateCoursIdBody
     */
    libelle: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateCoursIdBody
     */
    dateCour: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateCoursIdBody
     */
    heureDebut: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateCoursIdBody
     */
    heureFin: any;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof UpdateCoursIdBody
     */
    classesId?: any;
}
