/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateConvocationIdBody
 */
export interface UpdateConvocationIdBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateConvocationIdBody
     */
    libelle: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateConvocationIdBody
     */
    dateConvocation: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateConvocationIdBody
     */
    dateRdv: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateConvocationIdBody
     */
    statut: any;
    /**
     * 
     * @type {number}
     * @memberof UpdateConvocationIdBody
     */
    personnelId: any;
}
