/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdatePersonnelIdBody
 */
export interface UpdatePersonnelIdBody {
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    firstName: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    lastName: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    dateDeNaissance: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    lieuDeNaissance: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    photo?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    sexe: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    telephone: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonnelIdBody
     */
    fonction: any;
}
