/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * User unique email address
     * @type {string}
     * @memberof User
     */
    email: any;
    /**
     * username
     * @type {string}
     * @memberof User
     */
    username: any;
    /**
     * 
     * @type {Array&lt;Role&gt;}
     * @memberof User
     */
    roles?: any;
    /**
     * 
     * @type {Array&lt;Permission&gt;}
     * @memberof User
     */
    permissions?: any;
    /**
     * 
     * @type {Parents | Eleve | Professeur | Personnel}
     * @memberof User
     */
    model?: any;
    /**
     * Datetime marker of verification status
     * @type {Date}
     * @memberof User
     */
    emailVerifiedAt?: any;
    /**
     * User password
     * @type {string}
     * @memberof User
     */
    password: any;
    /**
     * 
     * @type {BaseModelpropertiescreatedAt}
     * @memberof User
     */
    createdAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesupdatedAt}
     * @memberof User
     */
    updatedAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesdeletedAt}
     * @memberof User
     */
    deletedAt?: any;
}
