/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthLoginBody
 */
export interface AuthLoginBody {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginBody
     */
    username: any;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginBody
     */
    password: any;
    /**
     * 
     * @type {boolean}
     * @memberof AuthLoginBody
     */
    persistent?: any;
}
