/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BaseModel
 */
export interface BaseModel {
    /**
     * Initial creation timestamp
     * @type {Date}
     * @memberof BaseModel
     */
    createdAt?: any;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof BaseModel
     */
    updatedAt?: any;
    /**
     * Soft delete timestamp
     * @type {Date}
     * @memberof BaseModel
     */
    deletedAt?: any;
}
