/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Classe
 */
export interface Classe {
    /**
     * 
     * @type {number}
     * @memberof Classe
     */
    id?: any;
    /**
     * Terminal
     * @type {string}
     * @memberof Classe
     */
    name: any;
    /**
     * Tle
     * @type {string}
     * @memberof Classe
     */
    shortName: any;
    /**
     * C
     * @type {string}
     * @memberof Classe
     */
    speciality: any;
    /**
     * 1
     * @type {number}
     * @memberof Classe
     */
    no: any;
    /**
     * 100
     * @type {number}
     * @memberof Classe
     */
    effectif: any;
    /**
     * 
     * @type {Eleve}
     * @memberof Classe
     */
    eleves?: any;
    /**
     * 
     * @type {Cour}
     * @memberof Classe
     */
    cours?: any;
    /**
     * 
     * @type {BaseModelpropertiescreatedAt}
     * @memberof Classe
     */
    createdAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesupdatedAt}
     * @memberof Classe
     */
    updatedAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesdeletedAt}
     * @memberof Classe
     */
    deletedAt?: any;
}
