/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20087
 */
export interface InlineResponse20087 {
    /**
     * 
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20087.ts
=======
<<<<<<< HEAD
     * @type {string}
     * @memberof InlineResponse20087
     */
    message?: any;
    /**
     * 
=======
>>>>>>> 7faa1c6 (maj reglement interieur)
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-site/src/generated/models/inline-response20087.ts
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     * @type {boolean}
     * @memberof InlineResponse20087
     */
    success?: any;
    /**
     * 
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20087.ts
     * @type {string}
=======
<<<<<<< HEAD
=======
>>>>>>> 0b7e9d7 (Testing)
     * @type {string}
     * @memberof InlineResponse20087
     */
    message?: any;
<<<<<<< HEAD
=======
    /**
     * 
>>>>>>> 7faa1c6 (maj reglement interieur)
     * @type {Suggestion}
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-site/src/generated/models/inline-response20087.ts
     * @memberof InlineResponse20087
     */
    message?: any;
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
     * @type {string}
     * @memberof InlineResponse20087
     */
    message?: any;
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
}
