/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20090
 */
export interface InlineResponse20090 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20090
     */
    success?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20090
     */
    message?: any;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20090.ts
>>>>>>> 0b7e9d7 (Testing)
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20090.ts
>>>>>>> 0b7e9d7 (Testing)
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
    /**
     * 
     * @type {Suggestion}
     * @memberof InlineResponse20090
     */
    content?: any;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
=======
=======
<<<<<<< HEAD
=======
    /**
     * 
     * @type {Array&lt;User&gt;}
     * @memberof InlineResponse20090
     */
    data?: any;
>>>>>>> 7faa1c6 (maj reglement interieur)
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-site/src/generated/models/inline-response20090.ts
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
}
