/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20089
 */
export interface InlineResponse20089 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20089
     */
    message?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20089
     */
<<<<<<< HEAD
<<<<<<< HEAD
    success?: any;
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20089.ts
    success?: any;
=======
    message?: any;
<<<<<<< HEAD
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-site/src/generated/models/inline-response20089.ts
>>>>>>> 0b7e9d7 (Testing)
=======
    success?: any;
>>>>>>> 707866f4 (Closes #318 -présentation du website)
    /**
     * 
     * @type {Suggestion}
     * @memberof InlineResponse20089
     */
    content?: any;
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 7faa1c6 (maj reglement interieur)
>>>>>>> 0b7e9d7 (Testing)
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
}
