/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
 * @interface InlineResponse40037Error
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response40037-error.ts
 * @interface InlineResponse40037Error
=======
<<<<<<<< HEAD:src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
 * @interface InlineResponse40033Error
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
 * @interface InlineResponse40037Error
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
 */
export interface InlineResponse40037Error {
    /**
     * 
     * @type {Array&lt;string&gt;}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     * @memberof InlineResponse40037Error
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response40037-error.ts
     * @memberof InlineResponse40037Error
=======
     * @memberof InlineResponse40033Error
========
 * @interface InlineResponse40030Error
 */
export interface InlineResponse40030Error {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof InlineResponse40030Error
>>>>>>>> 7faa1c6 (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40030-error.ts
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
     * @memberof InlineResponse40037Error
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     */
    email?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     * @memberof InlineResponse40037Error
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response40037-error.ts
     * @memberof InlineResponse40037Error
=======
<<<<<<<< HEAD:src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
     * @memberof InlineResponse40033Error
========
     * @memberof InlineResponse40030Error
>>>>>>>> 7faa1c6 (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40030-error.ts
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
     * @memberof InlineResponse40037Error
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     */
    username?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     * @memberof InlineResponse40037Error
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response40037-error.ts
     * @memberof InlineResponse40037Error
=======
<<<<<<<< HEAD:src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
     * @memberof InlineResponse40033Error
========
     * @memberof InlineResponse40030Error
>>>>>>>> 7faa1c6 (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40030-error.ts
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-admin/src/generated/models/inline-response40033-error.ts
>>>>>>> 0b7e9d7 (Testing)
<<<<<<< HEAD
=======
     * @memberof InlineResponse40037Error
>>>>>>> 707866f4 (Closes #318 -présentation du website)
=======
>>>>>>> da80021 (Closes #327 - Sanction prevu integrated)
     */
    password?: any;
}
