/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20082
 */
export interface InlineResponse20082 {
    /**
     * 
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 0b7e9d7 (Testing)
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
     * @type {boolean}
     * @memberof InlineResponse20082
     */
    success?: any;
    /**
     * 
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 7faa1c6 (maj reglement interieur)
>>>>>>> 0b7e9d7 (Testing)
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
     * @type {string}
     * @memberof InlineResponse20082
     */
    message?: any;
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20082.ts
=======
    /**
     * 
<<<<<<< HEAD
     * @type {Array&lt;SanctionPrevu&gt;}
=======
     * @type {boolean}
     * @memberof InlineResponse20082
     */
    success?: any;
    /**
     * 
     * @type {SanctionPrevu}
>>>>>>> 7faa1c6 (maj reglement interieur)
     * @memberof InlineResponse20082
     */
    content?: any;
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-site/src/generated/models/inline-response20082.ts
>>>>>>> 0b7e9d7 (Testing)
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
}
