/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20092
 */
export interface InlineResponse20092 {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20092
     */
    success?: any;
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 0b7e9d7 (Testing)
=======
>>>>>>> 707866f4 (Closes #318 -présentation du website)
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20092
     */
<<<<<<< HEAD
<<<<<<< HEAD
    message?: any;
=======
<<<<<<< HEAD:src/frontend/web/react-site/src/api/models/inline-response20092.ts
    message?: any;
=======
    data?: any;
=======
>>>>>>> 7faa1c6 (maj reglement interieur)
>>>>>>> fa5994b (maj reglement interieur):src/frontend/web/react-site/src/generated/models/inline-response20092.ts
>>>>>>> 0b7e9d7 (Testing)
=======
    message?: any;
>>>>>>> 707866f4 (Closes #318 -présentation du website)
}
