/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MembreConseil
 */
export interface MembreConseil {
    /**
     * 
     * @type {number}
     * @memberof MembreConseil
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof MembreConseil
     */
    idChef: any;
    /**
     * 
     * @type {number}
     * @memberof MembreConseil
     */
    idSurveillantG: any;
    /**
     * 
     * @type {number}
     * @memberof MembreConseil
     */
    idRepresentantE: any;
    /**
     * 
     * @type {Personnel}
     * @memberof MembreConseil
     */
    personnelC?: any;
    /**
     * 
     * @type {Personnel}
     * @memberof MembreConseil
     */
    personnelG?: any;
    /**
     * 
     * @type {Parents}
     * @memberof MembreConseil
     */
    parent?: any;
    /**
     * 
     * @type {BaseModelpropertiescreatedAt}
     * @memberof MembreConseil
     */
    createdAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesupdatedAt}
     * @memberof MembreConseil
     */
    updatedAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesdeletedAt}
     * @memberof MembreConseil
     */
    deletedAt?: any;
}
