/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MembreconseilsCreateBody
 */
export interface MembreconseilsCreateBody {
    /**
     * 
     * @type {number}
     * @memberof MembreconseilsCreateBody
     */
    idChef: any;
    /**
     * 
     * @type {number}
     * @memberof MembreconseilsCreateBody
     */
    idSurveillantG: any;
    /**
     * 
     * @type {number}
     * @memberof MembreconseilsCreateBody
     */
    idRepresentantE: any;
}
