/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {number}
     * @memberof Permission
     */
    id?: any;
    /**
     * Permission name
     * @type {string}
     * @memberof Permission
     */
    name: any;
    /**
     * Permission status
     * @type {number}
     * @memberof Permission
     */
    status?: any;
    /**
     * Permission description
     * @type {string}
     * @memberof Permission
     */
    description: any;
    /**
     * 
     * @type {BaseModelpropertiescreatedAt}
     * @memberof Permission
     */
    createdAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesupdatedAt}
     * @memberof Permission
     */
    updatedAt?: any;
    /**
     * 
     * @type {BaseModelpropertiesdeletedAt}
     * @memberof Permission
     */
    deletedAt?: any;
}
