/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SanctionprevusCreateBody
 */
export interface SanctionprevusCreateBody {
    /**
     * 
     * @type {string}
     * @memberof SanctionprevusCreateBody
     */
    libelle: any;
    /**
     * 
     * @type {string}
     * @memberof SanctionprevusCreateBody
     */
    dureeValidite: any;
    /**
     * 
     * @type {number}
     * @memberof SanctionprevusCreateBody
     */
    eleveId: any;
    /**
     * 
     * @type {number}
     * @memberof SanctionprevusCreateBody
     */
    fauteId: any;
}
