/* tslint:disable */
/* eslint-disable */
/**
 * Mon API
 * Documentation de l'API de votre application.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateConseilDisciplineIdBody
 */
export interface UpdateConseilDisciplineIdBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateConseilDisciplineIdBody
     */
    dateCd: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateConseilDisciplineIdBody
     */
    heureDebutCd: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateConseilDisciplineIdBody
     */
    heureFinCd: any;
    /**
     * 
     * @type {number}
     * @memberof UpdateConseilDisciplineIdBody
     */
    eleveId: any;
    /**
     * 
     * @type {number}
     * @memberof UpdateConseilDisciplineIdBody
     */
    fauteId: any;
}
