name: Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    defaults:
        run:
          working-directory: ./src/frontend/web/react-admin
          
    strategy:
      matrix:
        node: [ '16' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
